"""Small independently checked grammar specimens; no corpus execution."""
EXPRESSIONS = [
    "'a\\\r\nb'", "00e5", "0_0.2",
    "*a", "a[*b]", "a[*b,]", "f(*a if b else c)", "f(**a if b else c)",
    "((a,b))", "(())", "f(x=1,x=2)",
    "a + b * c ** d ** e", "-2**2", "2**-2", "~-+x", "not not x",
    "a or b or c", "a and b and c", "a or b and not c", "(a and b) and c",
    "a and (b and c)", "a < b <= c != d is e is not f in g not in h",
    "(a < b) < c", "a < (b < c)", "not a in b", "a not in b",
    "a if b else c if d else e", "(a if b else c) if d else e",
    "a | b ^ c & d << e + f * g", "a @ b // c % d / e - f",
    "()", "(a)", "((a))", "(a,)", "a,", "a,b,c", "(a,b,c)",
    "[]", "[a,b,]", "[*a,b]", "{}", "{a}", "{a,b,}", "{*a,b}",
    "{a:b,c:d,}", "{**a, b:c, **d}", "f()", "f(a,b,)", "f(*a,b,*c)",
    "f(a,k=b,**c)", "f(k=a,*b)", "f(**a,**b)", "f(a)(b).x[c]",
    "(a).b", "(f)(a)", "(a)[b]", "a[b,c]", "a[b,]", "a[(b,c)]",
    "(a)+b", "a+(b)", "-(a)", "(a) if (b) else (c)",
    "0x1_f", "1_000", "1.25e-9", "1e999", "3j", "True", "False", "None", "...",
    "'a' 'b'", "('a' # comment\n 'b')", "u'hello'", "U'hello'", "r'\\n'", "b'abc' b'def'",
    "'''two\nlines'''", "'é😀'", "( 'é' ).upper()", "x[(a)]", "([a, b])",
    'f""', "f'a'", 'f"{x}"', 'f"a{b}c"', 'F"{x}" Rf"{y}\\n" fR\'{z}\'', 'f"{x!r}{y!s}{z!a}"', 'f"{x:>10}"', 'f"{x!r:>{w}}"', 'f"{x:}"', 'f"{x:}}}"', 'f"{x:a{y}b{z!r}c}"',
    'f"{x:{{y}}}"', 'f"{x:{y:>5}}"', 'f"{d:%Y-%m-%d %H:%M}"', 'f"{x:!r}"', 'f"{x::}"', 'f"{x=}"', 'f"{x = }"', 'f"{x=!s}"', 'f"{x=:>10}"', 'f"{x=  !r:>5}"', 'f"{a>=b=}"',
    'f"{a!=b}"', 'f"{a==b!r}"', 'f"{a<b>c:d}"', 'f"{a<=b}{c>=d}"', 'f"{ a }"', 'f"{a, b}"', 'f"{ (a) , }"', 'f"{*a, b}"', 'f"{a, b!r}"', 'f"{(lambda x: 1)}"', 'f"{ {1: 2}[1] }"',
    'f"{a[1:2]}"', 'f"{f(a, k=b)[::2].c}"', 'f"{a if b else c:>{d if e else f}}"', 'f"{{x}}{{"', 'f"{a}}}"', 'f"{{{a}}}"', 'f"\\{x}"', 'rf"\\{x}"', 'rf"{a}\\{b}\\n"',
    'f"\\N{DIGIT ONE}{x}\\x41\\u00e9\\\\"', 'f"{x:\\n}"', 'f"a\\\n{x}"', 'f"{\'a\'}{\'\'\'b\'\'\'}"', 'f"{f\'{x}\'}"', 'f\'\'\'{f"{f\'{x}\'}"}\'\'\'', '"" f"{x}"',
    '"a" f"b{x}" \'c\' f\'d\'', 'u"a" f"{x}" "b"', '"a" u"b" f"{x}"', 'u"" f"{x:a}" "b"', 'f"{x}" u"a"', 'r"\\d" f"{x}" "\\n"', 'f"é{x}é{y + 1}😀"', '(f"é{x}"\n  f"é{y + 1}")',
    'f"""a\n  {b} and {\nc} z {  d\n + e}"""', 'f"""{x:\n>{w}}"""', 'f"""{x\n=}"""', 'f\'\'\'"{x}" \'{y}\\\'\'\'\'', 'f"{x}".format(y)', 'f"{x}"[1:]', 'f(f"{x}", k=f"{y}")',
    'u"" f"{x:a{y}b}" "b"', '"pp" f"{x:{y}b}" f"{z:c{w:d}}"', 'u"p" f"""{x:{y}b\n}""" f"{z:c{w:d}}"',
    # Fuel: an f-string's fields outnumber its one token; the budget weighs a STRING by its characters.
    'f"' + "{a}x" * 300 + '"', 'f"{x:' + "{w}." * 300 + '}"', 'f"{f\'' + "{a!r:>3}" * 300 + '\'}"',
]
STATEMENTS = [
    "match=1", "case=2", "return *a", "a = *b", "x += *a",
    "x=1", "x=y=z", "a,b = c", "[a,*b] = c", "(a) = b", "a.b = c",
    "a[b] = c", "a[b,c] = d", "a.b[c].d = e", "a += b", "a[b] **= c",
    "a @= b", "a <<= b", "a |= b", "a += b,c", "a = (b)", "(a)",
    "pass; break; continue", "return", "return a,b", "return (a)", "x=1; y=2;",
    "if a: pass", "if a: x=1; y=2\nelse: pass",
    "if a:\n    pass\nelif b:\n    return c\nelse:\n    continue\n",
    "if a:\n    if b:\n        pass\n    else:\n        break\nelse:\n    pass\n",
    "while a:\n    x += 1\nelse:\n    return x\n",
    "if (a):\n\tpass\n\n# blank\nelse:\n\treturn (b)\n",
    "if a:\r\n    pass\r\nelse:\r\n    break\r\n",
    "if a:\n \f  pass\n", "x = ('a' # one\n 'b')\n",
    "x = 1 + \\\n 2\n", "x=1\n# trailing comment", "# just a comment", "\n\n",
]
# P4: functions, loops, and the remaining simple/compound statements.
STATEMENTS += [
    # A compound statement ends at its last non-whitespace token, so a trailing `;` extends it.
    "if a: x;", "if a:\n    x;\n", "while a:\n    if b:\n        x;\n", "def f():\n    return 1;\n", "for a in b: x; y;",
    "try:\n    x;\nfinally:\n    y;\n", "with a:\n    x;\n", "if a:\n    x;\nelse:\n    y;\n", "try:\n    x\nexcept E:\n    y;\n",
    "lambda: 0", "lambda x: x", "lambda x, y=1, *a, z, w=2, **k: (x, y)", "lambda *, a: a", "lambda a, /, b: a",
    "lambda x=lambda: 1: x", "f(lambda: x, y)", "[lambda: 1, lambda *a: a]", "x = lambda: a if b else c",
    "a if b else lambda: c", "(lambda x: x)(1)", "lambda x,: x", "lambda **k: k", "f(key=lambda t: t[0])",
    "def f(): pass", "def f(a, b=1, *args, c, d=2, **kw): return a",
    "def f(a: int, /, b: 'str' = 'x', *, c: list = [], **kw: dict) -> None:\n    pass\n",
    "def f(*args: int, **kw: str) -> 'T':\n    return args\n", "def f(*a: *T): pass", "def f(a, /): pass",
    "def f(*, a): pass", "def f(a,): pass", "def f(**k,): pass", "def f(*a,): pass", "def f(a=1, /, b=2, *, c): pass",
    "def f(a, b=1, /, c=2): pass", "def f(*, a, b=1, c): pass",
    "def outer():\n    def inner(x):\n        return x\n    return inner\n",
    "def f():\n    'doc'\n    global a, b\n    a = 1\n\ndef g():\n    x = 1\n    def h():\n        nonlocal x\n        x = 2\n",
    "@d\ndef f(): pass", "@a.b(c)\n@d\n\n# comment\ndef f(x):\n    return x\n", "@(lambda f: f)\ndef g(): pass",
    "if a:\n    @d\n    def f():\n        pass\n",
    "for x in y: pass", "for a, b in c:\n    pass\nelse:\n    break\n", "for (a, b) in c: pass", "for [a, b] in c: pass",
    "for *a, b in c: pass", "for x, in y: pass", "for a.b in c: pass", "for a[0] in c: pass", "for x in *a, b: pass",
    "for x in a, b: pass", "for x in a if b else c:\n    continue\n", "for i in range(10):\n    for j in i:\n        pass\n",
    "for x in y:\n    pass\nx = 1\n", "for x in (yy): pass", "for ((a), b) in c: pass",
    "global a", "global a, b", "nonlocal a", "del a", "del a, b", "del (a, b)", "del a,", "del [a, b]", "del a.b, c[0]",
    "del (a), (b)", "del ()", "del (a)", "del a[1], (b, [c, d])",
    "assert a", "assert a, 'msg'", "assert (a, b)", "assert a if b else c, (d)",
    "raise", "raise E", "raise E('x') from None", "raise (E)", "raise E from (c)",
    "try:\n    pass\nexcept:\n    pass\n", "try: pass\nexcept E: pass", "try: pass\nfinally: pass",
    "try:\n    a\nexcept E as e:\n    b\nexcept (F, G):\n    c\nelse:\n    d\nfinally:\n    e\n",
    "try:\n    a\nexcept E:\n    b\nelse:\n    c\n", "try:\n    a\nexcept:\n    b\nexcept E:\n    c\n",
    "try:\n    try:\n        a\n    finally:\n        b\nexcept a.b as c:\n    raise\n",
    "def f():\n    try:\n        return 1\n    except E:\n        pass\n    x = 2\n",
    "with a: pass", "with a as b: pass", "with a as b, c as d:\n    pass\n", "with a, b: pass", "with (a, b): pass",
    "with (a as b): pass", "with (a as b, c as d,): pass", "with (a, b) as c: pass", "with (a) as b: pass", "with (a).b: pass",
    "with (a): pass", "with (): pass", "with a as (b, c): pass", "with a as [b, *c]: pass", "with a as b.c, d as e[0]: pass",
    "with (\n    a as b,\n    c as d\n):\n    pass\n", "with f(x) as y, (g(z)): pass", "with (a, b), c: pass", "with (yy) as b, c: pass",
    "match in x", "x = [i, in_]", "*a = 1", "*a, = 1", "[*a] = 1", "for *a in y: pass", "with a as *b: pass", "with a as *b, c: pass",
]
# P5: imports. alias spans run from the first name token to the asname; ImportFrom ends at `)`.
STATEMENTS += [
    "import a", "import a.b.c", "import a as b", "import a.b as c, d, e.f as g", "import a . b", "import a; import b;",
    "from a import b", "from a.b import c as d, e", "from a import (b)", "from a import (b, c,)", "from a import (b as c, d as e)",
    "from a import (\n    b,\n    c as d,  # note\n)\n", "from a import *", "from . import a", "from .. import a", "from ... import a",
    "from .... import a", "from ..... import a", "from .a import b", "from ..a.b import c", "from ...a import b", "from . . import a",
    "from .import a", "from . a import b", "from .a import *", "from __future__ import annotations", "from a import b as c; x = 1",
    "from a \\\n    import b", "if a:\n    import b\nelse:\n    from c import d\n", "def f():\n    from . import g\n    return g\n",
    "try:\n    import a\nexcept ImportError:\n    a = None\n", "import match, case", "from match import case as _",
    "from a import (b as c)", "import a  # é",
]
# P6: classes. ClassDef starts at `class` (decorators excluded) and ends with its body.
STATEMENTS += [
    "class A: pass", "class A(): pass", "class A(B): pass", "class A(B, C,): pass", "class A(B, metaclass=M): pass",
    "class A(metaclass=M, **kwds): pass", "class A(*bases, **kwds): pass", "class A(B.C, D[E], f(x), x=1, *y): pass",
    "class A(B,\n        C):\n    pass\n", "@d\nclass A: pass", "@d1\n@d2(x)\n@a.b\nclass A(B):\n    pass\n",
    "class A:\n    \"\"\"doc\"\"\"\n", "class A:\n    'doc'\n    x = 1\n    def f(self):\n        return self.x\n",
    "class A:\n    class B:\n        class C(A): pass\n    y = B\n", "class A:\n    @staticmethod\n    def f(): pass\n    @d\n    class B: pass\n",
    "def f():\n    class A(object):\n        pass\n    return A\n", "if a:\n    class A: pass\nelse:\n    class A(B): x = 1; y = 2\n",
    "class A: x = 1; y = 2", "class A(B): import c", "class match: pass", "class A(B if c else D, lambda: 1): pass",
    "class A:\n\n    # comment\n\n    def f(self): pass\n\n    # trailing\nx = 1\n", "class A(\n    B,  # note\n    metaclass=M,\n):\n    pass\n",
    "class A:\n    def __init__(self, a, *b, c=1, **d):\n        self.a = a\n        for i in b:\n            try:\n                pass\n            finally:\n                del i\n",
    "@d(x)\nclass A(B, *c, metaclass=M, **k):\n    \"doc\"\n    class C: pass\n    def f(self):\n        return 1\nclass D(): y = 1\n",
    "class A: pass  # é", "class A(x=1, *y): pass", "class A(**k, x=1): pass",
]
# P7: slices. A Slice spans its first token (a bound or the first `:`) to its last (a bound or the last `:`).
STATEMENTS += [
    "a[:]", "a[::]", "a[1:]", "a[:2]", "a[::3]", "a[1:2]", "a[1:2:3]", "a[1::3]", "a[:2:3]", "a[1:2:]", "a[1::]", "a[:2:]",
    "a[i, j]", "a[:, 1]", "a[1, :]", "a[:, :]", "a[1:2, ::3]", "a[1:2,]", "a[:,]", "a[::, ::,]", "a[..., 1:2]", "a[*b, 1:2]", "a[1:2, *b]",
    "f(x)[1:]", "a.b[:-1]", "a[1][2:3]", "a[b[1:2]:c[::2]]", "a[b[:]]", "a[1:2][3:4][5]", "f(a[1:])[::-1].g()[x:y]", "'abc'[1:]", "[1, 2][::-1]",
    "(a)[(1):(2):(3)]", "a[ : ]", "a[1 : 2 : 3]", "a[\n    1:\n    2\n]", "a[-1:]", "a[not b:c or d]", "a[b if c else d:e if f else g]",
    "a[lambda: 1:2]", "a[lambda x: x:lambda: y:lambda: z]", "a[x:y, lambda: 1]", "a[b < c:d]", "a[(b, c):d]", "a[{1: 2}[1]:]",
    "a[1:2] = b", "a[:] = b[:] = c", "a[::2], b[1:] = c", "a[1:2] += b", "a[:, 0] *= 2", "[a[1:], *b[::2]] = c",
    "del a[1:2]", "del a[:], b[::2], (c[1:], [d[:1]])", "for a[1:2] in b: pass", "with a as b[1:2]: pass", "with a[1:2]: pass",
    "def f(a=b[1:], *c: d[:2]) -> e[::3]:\n    return a[1:-1]\n", "@a[1:2]\ndef f(): pass",
    "if a[1:]:\n    x = a[:1]\nelif a[::2]:\n    pass\n", "assert a[1:2], b[:]", "raise E(a[1:]) from b[:1]", "return a[1:], b[:2]",
    "x = a[1:2] if a[:1] else a[2:]", "f(a[1:], k=b[:2], *c[::2], **d[3:])", "{a[1:]: b[:2], **c[::3]}", "a[1:2] # é", "a[b[1:]][:-1].c()[x:y, ::2] = d[:]\ndel a[1:2:3], e[*f, :g]\n", "'é😀'[1:] + a[2:]",
    "f'{x}'", "a[1:f'{x}']", 'x = f"a{b}c"', 'if 1:\n    x = (f"a"\n         f"""b\n   {c:>{d}} {e!r}""")', 'raise E(f"bad {name!r}: {value:.2f}") from None',
    'def f(a=f"{b}") -> f"{c}":\n    return f"{a=}"', 'class A(B):\n    f"not a doc {x}"\n    y = f"{z}"', 'assert x, f"{x} != {y}"', 'with open(f"{d}/{n}.txt") as h: pass',
    'x = {f"{k}": f"{v:>{w}}", **d}', 'for x in f"{y}": pass', 'log.info("a"\n         f"{b}"\n         "c")', 'x = f"{a}" if f"{b}" else f"{c}" + "d" f"{e}"',
]

# P9: comprehensions. ListComp/SetComp/DictComp span their brackets; a GeneratorExp its parentheses, the call's when it is the sole argument.
STATEMENTS += [
    "[x for x in y]", "{x for x in y}", "{x:x for x in y}", "(x for x in y)", "f(x for x in y)", "for x in [y for y in z]: pass",
    "a[(x for x in y):]", "a[[x for x in y][0]:]", 'f"{[x for x in y]}"', '"a" f"{sum(x for x in y)}"', 'f"{x:{[y for y in z][0]}}"', 'f"{x for x in y}"', 'f"{ {k: v for k, v in d}!r:>{max(w for w in ws)}}"',
    "[x for x in y if z]", "[x for x in y if a if b]", "[x for x in y for z in x]", "[x for x in y if a for z in x if b if c for w in z]",
    "[x for x, in y]", "[x for x, y in z]", "[x for *a, b in y]", "[x for *a in y]", "[x for a.b, c[0], (d, [e]) in y]", "[x for (x) in y]", "[x for [a, b] in y]", "[x for a[1:2] in y]",
    "[x for x in not y]", "[x for x in y or z]", "[x for x in y in z]", "[x for x in a < b]", "[x for x in y if x not in z]", "[x for x in y if a or b if not c]", "[x for x in (a, b)]", "[x for x in (y) if (z)]",
    "[a if b else c for a in d]", "{a: b if c else d for a in e}", "{a if b else c: d for a in e}", "[lambda: x for x in y]", "[lambda x: x for x in y if (lambda: 1)]", "[(x, y) for x in a for y in b]",
    "[x for x in (lambda: y)]", "[x for x in (a if b else c)]", "[x for x in y if (a if b else c)]", "[[x for x in y] for y in z]", "[[[a for a in b] for b in c] for c in d]",
    "{(x for x in y) for y in {z: w for z in q}}", "[x for x in [y for y in [z for z in w]]]", "[x for x in y if [z for z in x if {w for w in z}]]", "{a: [b for b in a] for a in {c for c in d}}",
    "((x for x in y))", "((x) for x in y)", "( x for x in y )", "[ x for x in y ]", "{ x for x in y }", "{ a : b for a in c }", "f( x for x in y )", "f((x for x in y))", "f((x for x in y), 1)", "f(a, (x for x in y))",
    "f(x for x in y)(z)", "f(x for x in y).a", "f(x for x in y)[0]", "f(g(x for x in y) for y in z)", "a.b.c(x for x in y)", "f(x)(y for y in z)", "f(*[x for x in y], **{k: v for k, v in z})", "f(k=[x for x in y])",
    "print(x for x in y if z)", "sum(x\n for x in y)", "[x for\n x in y\n if z]", "x = [\n    a  # note\n    for a in b  # more\n    if a\n]\n", "x = {\n    k: v\n    for k, v in d.items()\n    if v\n}\n", "x = sum(\n    a * b\n    for a, b in zip(p, q)\n)\n",
    "x = (\n    a\n    for a in b\n)", "[x for x in y][0]", "[x for x in y].sort()", "(x for x in y).send", "{x for x in y} | {z}", "[x for x in y] + [z for z in w]", "not [x for x in y]", "-len([x for x in y])",
    "a[(x for x in y)]", "a[[x for x in y]]", "a[[x for x in y]:{z for z in w}]", "a[x, [y for y in z]]", "a[[i for i in j]] = [k for k in l]", "x = y = [z for z in w]", "x += [z for z in w]", "x, y = (z for z in w), 1",
    "with (x for x in y): pass", "with (x for x in y) as z, [a for a in b] as c: pass", "with ([x for x in y] as z): pass", "@f(x for x in y)\ndef g(): pass", "@[d for d in e][0]\nclass A([b for b in c][0], k={x for x in y}): pass",
    "def f(a=[x for x in y], *b: {k: v for k in z}) -> (t for t in u):\n    return [a for a in b if a]\n", "lambda a=[x for x in y]: (z for z in a)", "if [x for x in y]:\n    pass\nelif {z for z in w}:\n    pass\n",
    "while any(x for x in y): break", "for a, b in ((x, y) for x in p for y in q): pass", "assert all(x for x in y), [z for z in w]", "raise E([x for x in y]) from (z for z in w)", "return [x for x in y], {z for z in w}",
    "del a[[x for x in y][0]]", "try:\n    pass\nexcept tuple(e for e in es) as err:\n    pass\n", "class A:\n    x = [i for i in range(3)]\n    y = {i: i for i in x}\n", "[x for x in y]; {z for z in w}", "x = ['é😀' for a in 'é😀'] # é",
    "[x for x in y if z is not None and w not in v]", "{**a, 'k': [x for x in y]}", "[*a, [x for x in y]]", "{*a, (x for x in y)}", "(a, [x for x in y])", "([x for x in y],)", "x = [a.b(c)[d] for a in e.f() if a.g]",
    "[x for x in y if z]if w else[v for v in u]", "[x for x in range(10) if x % 2 == 0 for y in range(x) if y]", "{k: {j: i for j in k} for k in l if k for i in k}", "[f'{x}' for x in y if f'{x:>{w}}']", "[x[1:] for x[0] in y[::2] if x[:1]]",
    "x = {k: [v for *v, in k if v] for k in d}\nf({g(a, b)} for a, (b, c[0]) in z if a if b for c.d in a)\n",
    "f(x for x in y)\ng(z for z in w)\n", "if 1:\n    x = [a\n         for a in b]\n    y = 1\n", "[1 for _ in y]", "[... for x in ...]", "[None for None_ in y]", "[x for x in y if 1 if 2 if 3]",
]

INVALID = [
    "'\0'", "#\0",
    "b'a' 'b'",
    "(*a)", "f(**a,*b)", "{*a:b}", "[*a if b else c]",
    "x =", "1 = x", "f() = x", "(a+b) = c", "[a,1] = c", "a,b += c",
    "if x\n pass", "if x:\npass", "if x: if y: pass", "else: pass",
    "x y", "f(a b)", "[a b]", "{a b}", "f(x=1,2)", "a + not b",
    "a is not", "a not b", "(]", "'''unfinished", "if x:\n    pass\n  pass",
    "lambda x y: x", "1 + lambda: 1", "not lambda: 1", "lambda a=1, b: a", "lambda *: 1", "lambda *, **k: 1",
    "lambda /: 1", "lambda a, /, b, /: 1", "lambda *a, *b: 1", "lambda **k, a: 1", "lambda *, /: 1",
    "def f(a=1, b): pass", "def f(*): pass", "def f(*,): pass", "def f(**k, a): pass", "def f(/): pass", "def f(*a=1): pass",
    "def f(a, *, /): pass", "def f: pass", "def f()", "def f(a b): pass", "def (a): pass", "@d\nx = 1", "@d", "def f() -> : pass",
    "for x y: pass", "for x in: pass", "for 1 in y: pass", "for a + b in y: pass", "for f() in y: pass",
    "for x in y: pass\nelse x", "a, in b",
    "global", "global a.b", "global a,", "nonlocal 1", "del", "del 1", "del a + b", "del *a", "del *a, b", "del f()", "del (*a, b)",
    "assert", "assert a,", "raise from x", "raise a from", "raise a, b",
    "try: pass", "try: pass\nelse: pass", "try: pass\nelse: pass\nfinally: pass", "try: pass\nexcept E as: pass",
    "try: pass\nexcept E as a.b: pass", "try: pass\nexcept E, F: pass", "try: pass\nfinally: pass\nexcept: pass",
    "try: pass\nexcept as e: pass", "except: pass", "finally: pass",
    "class", "class A", "class: pass", "class A(: pass", "class A(B: pass", "class A) : pass", "class A(B)", "class 1: pass", "class A.B: pass",
    "class A(B,,): pass", "class A(x=1, y): pass", "class A(**k, *y): pass", "class if: pass", "class A:", "class A:\npass", "class A pass",
    "@d\nx = 1", "@d\nimport a", "@\nclass A: pass", "@d class A: pass", "class A[B]: pass", "class A(B) -> C: pass", "x = class A: pass",
    "import", "import a,", "import a.", "import .a", "import a as", "import a as b.c", "import (a)", "import *", "import a b", "import if",
    "from a", "from import b", "from a import", "from a import b,", "from a import ()", "from a import (b", "from a import (*)",
    "from a import *, b", "from a import b, *", "from a import b.c", "from a import (b.c)", "from a. import b", "from a import b as",
    "from a import b as 1", "from .. import", "from a import (b,,)", "from a import (,)", "x = import a", "from a import b c",
    "a[]", "a[1:2:3:4]", "a[:::]", "a[*b:1]", "a[1:*b]", "a[1:2:*b]", "a[:", "a[1:2", "a[,]", "a[1:2,,]", "a[1 2]", "a[1:2 3]", "a[:] = ", "[1:2]", "(1:2)",
    "f(1:2)", "{1:2:3}", "x = 1:2", "a[1:2] = 1:2", "del a[1:2:3:4]", "a[1:]]", "a[1:pass]", "a[1:2)", "f(a[1:2]=3)", "for a[1:] in: pass",
    "with: pass", "with a as: pass", "with a as 1: pass", "with a, : pass", "with a as f(): pass", "with (a as b) as c: pass",
    'f"{x!r }"', 'f"{x! r}"', 'f"{x!z}"', 'f"{x!}"', 'f"{}"', 'f"{ }"', 'f"{!r}"', 'f"{:>5}"', 'f"{=}"', 'f"{x"', 'f"{x!r"', 'f"{x:>5"', 'f"x}"', 'f"{a b}"', 'f"{x#}"',
    'f"{\'\\n\'}"', 'f"""{a\\\n}"""', 'f"{lambda x: 1}"', 'f"{x}" b"a"', 'b"a" f"{x}"', 'f"{*a}"', 'f"{x!r!s}"', 'f"{a}}"', 'f"{x:{y}}}"', 'f"{x:{{}"', 'f"{x:{y:{z}}}"',
    'f"{x:{}}"', 'f"{(a}"', 'f"{a)}"', 'f"{a]}"', 'f"{[a)}"', 'f"{\'a}"', 'f"{a = b}"', 'f"{a=b}"', 'f"{x:{y!z}}"', 'f"{1 +}"', 'f"{x} {" "y}"', 'x = f"{pass}"', 'f"{x}" = 1',
    'del f"{x}"', 'f"{x}" += 1', 'for f"{x}" in y: pass',
    "f(x for x in y,)", "f(x for x in y, 1)", "f(1, x for x in y)", "f(x for x in y, k=1)", "f(k=1, x for x in y)", "f(x=1 for x in y)", "f(*x for x in y)", "f(**x for x in y)", "f(a, for x in y)",
    "class A(x for x in y): pass", "class A(B, x for x in y): pass", "a[x for x in y]", "a[1:x for x in y]", "[*a for a in b]", "(*a for a in b)", "{**a for a in b}", "{*a for a in b}", "{a: *b for a in c}",
    "[a, b for a in c]", "(a, b for a in c)", "{a, b for a in c}", "{a: b, c: d for a in e}", "{a: b, for a in c}", "[x, for x in y]", "(x, for x in y)", "[x for x in a, b]", "[x for x in y,]", "{a: b for a in c, }",
    "[x for x in lambda: y]", "[x for x in y if lambda: 1]", "[x for x in a if b else c]", "[x for x in y if z else w]", "[x if y for x in z]", "[x for x in y if a, b]", "[x for x in *y]", "[x for x in y if *z]",
    "[x for 1 in y]", "[x for not x in y]", "[x for a + b in y]", "[x for f() in y]", "[x for x in]", "[for x in y]", "[x for in y]", "[x for x y]", "[x for x]", "[x for]", "{a: b for a in c for}", "[x for x in y if]", "[x for x in y for]",
    "(x for x in y", "[x for x in y", "{x for x in y", "{a: b for a in c", "f(x for x in y", "[x for x in y)", "(x for x in y]", "{x for x in y]", "f(x for x in y]", "[x for x in y}",
    "x for x in y", "x = y for y in z", "return x for x in y", "[x for x in y] = 1", "(x for x in y) = 1", "{x for x in y} = 1", "{a: b for a in c} = 1", "del [x for x in y]", "del (x for x in y)", "[x for x in y] += 1",
    "for [x for x in y] in z: pass", "with a as [x for x in y]: pass", "[x for x in y for]", "[x for x in y if z for]", "[x for [x for x in y] in z]",
    "if x: for y in z: pass", "x = for", "lambda: for", "[x for x in y] [z for z in w]", "(x for x in y) (z for z in w) w", "{x: for x in y}", "{x for x in y: z}", "[x for x in y: z]", "f(x for x in y)(", "[x\nfor x in y\n", 'f"{x for x in}"', 'f"{[x for x in y}"', 'f"{x:{y for}}"',
]

UNSUPPORTED = [
    "K", "a.K", "f(K=1)", "match x:\n    case _: pass\n",
    "import é", "import a as é", "from é import a", "from a import é", "from a import b as é", "class é: pass", "class A(é): pass", "class A(é=1): pass", "class A:\n    x: int = 1\n", "class A:\n    async def f(self): pass\n", "@d\nclass A:\n    def f(self): yield\n", "async def f(): pass", "@d\nasync def f(): pass",
    "async for x in y: pass", "async with a: pass", "def f(): yield", "def f(): x = yield y", "lambda: (yield)", "def f(é): pass", "lambda é: 1",
    "global é", "try: pass\nexcept E as é: pass", "try: pass\nexcept* E: pass", "def f(): await x", "def f(a: int): x: int = 1", "(x := 1)", "with (x := 1): pass",
    "a[x:=1]", "a[1:(x:=2)]", "a[é:]", "a[1:é]", "a[::é]", "a[1:, é]", "a[1:2].é", "a[await b:]",
    'f"{(x := 1)}"', 'f"{(yield)}"', 'f"{await x}"', 'f"{é}"', 'f"{a.é}"', 'f"{x:{é}}"',
    "[x async for x in y]", "(x async for x in y)", "{x async for x in y}", "{a: b async for a in c}", "f(x async for x in y)", "[x for x in y async for z in w]", "[await x for x in y]", "[x for x in await y]",
    "[x := 1 for x in y]", "[x for x in (y := z)]", "[x for x in y if (z := x)]", "f(x := 1 for x in y)", "{(k := a): b for a in c}", "[(yield) for x in y]", "[é for x in y]", "[x for é in y]", "[x for x in é]", "[x for x in y if é]", "f(é for x in y)",
]
