"""Small independently checked grammar specimens; no corpus execution."""
EXPRESSIONS = [
    "'a\\\r\nb'", "00e5", "0_0.2",
    "*a", "a[*b]", "a[*b,]", "f(*a if b else c)", "f(**a if b else c)",
    "((a,b))", "(())", "f(x=1,x=2)",
    "a + b * c ** d ** e", "-2**2", "2**-2", "~-+x", "not not x",
    "a or b or c", "a and b and c", "a or b and not c", "(a and b) and c",
    "a and (b and c)", "a < b <= c != d is e is not f in g not in h",
    "(a < b) < c", "a < (b < c)", "not a in b", "a not in b",
    "a if b else c if d else e", "(a if b else c) if d else e",
    "a | b ^ c & d << e + f * g", "a @ b // c % d / e - f",
    "()", "(a)", "((a))", "(a,)", "a,", "a,b,c", "(a,b,c)",
    "[]", "[a,b,]", "[*a,b]", "{}", "{a}", "{a,b,}", "{*a,b}",
    "{a:b,c:d,}", "{**a, b:c, **d}", "f()", "f(a,b,)", "f(*a,b,*c)",
    "f(a,k=b,**c)", "f(k=a,*b)", "f(**a,**b)", "f(a)(b).x[c]",
    "(a).b", "(f)(a)", "(a)[b]", "a[b,c]", "a[b,]", "a[(b,c)]",
    "(a)+b", "a+(b)", "-(a)", "(a) if (b) else (c)",
    "0x1_f", "1_000", "1.25e-9", "1e999", "3j", "True", "False", "None", "...",
    "'a' 'b'", "('a' # comment\n 'b')", "u'hello'", "U'hello'", "r'\\n'", "b'abc' b'def'",
    "'''two\nlines'''", "'é😀'", "( 'é' ).upper()", "x[(a)]", "([a, b])",
]
STATEMENTS = [
    "match=1", "case=2", "return *a", "a = *b", "x += *a",
    "x=1", "x=y=z", "a,b = c", "[a,*b] = c", "(a) = b", "a.b = c",
    "a[b] = c", "a[b,c] = d", "a.b[c].d = e", "a += b", "a[b] **= c",
    "a @= b", "a <<= b", "a |= b", "a += b,c", "a = (b)", "(a)",
    "pass; break; continue", "return", "return a,b", "return (a)", "x=1; y=2;",
    "if a: pass", "if a: x=1; y=2\nelse: pass",
    "if a:\n    pass\nelif b:\n    return c\nelse:\n    continue\n",
    "if a:\n    if b:\n        pass\n    else:\n        break\nelse:\n    pass\n",
    "while a:\n    x += 1\nelse:\n    return x\n",
    "if (a):\n\tpass\n\n# blank\nelse:\n\treturn (b)\n",
    "if a:\r\n    pass\r\nelse:\r\n    break\r\n",
    "if a:\n \f  pass\n", "x = ('a' # one\n 'b')\n",
    "x = 1 + \\\n 2\n", "x=1\n# trailing comment", "# just a comment", "\n\n",
]
# P4: functions, loops, and the remaining simple/compound statements.
STATEMENTS += [
    # A compound statement ends at its last non-whitespace token, so a trailing `;` extends it.
    "if a: x;", "if a:\n    x;\n", "while a:\n    if b:\n        x;\n", "def f():\n    return 1;\n", "for a in b: x; y;",
    "try:\n    x;\nfinally:\n    y;\n", "with a:\n    x;\n", "if a:\n    x;\nelse:\n    y;\n", "try:\n    x\nexcept E:\n    y;\n",
    "lambda: 0", "lambda x: x", "lambda x, y=1, *a, z, w=2, **k: (x, y)", "lambda *, a: a", "lambda a, /, b: a",
    "lambda x=lambda: 1: x", "f(lambda: x, y)", "[lambda: 1, lambda *a: a]", "x = lambda: a if b else c",
    "a if b else lambda: c", "(lambda x: x)(1)", "lambda x,: x", "lambda **k: k", "f(key=lambda t: t[0])",
    "def f(): pass", "def f(a, b=1, *args, c, d=2, **kw): return a",
    "def f(a: int, /, b: 'str' = 'x', *, c: list = [], **kw: dict) -> None:\n    pass\n",
    "def f(*args: int, **kw: str) -> 'T':\n    return args\n", "def f(*a: *T): pass", "def f(a, /): pass",
    "def f(*, a): pass", "def f(a,): pass", "def f(**k,): pass", "def f(*a,): pass", "def f(a=1, /, b=2, *, c): pass",
    "def f(a, b=1, /, c=2): pass", "def f(*, a, b=1, c): pass",
    "def outer():\n    def inner(x):\n        return x\n    return inner\n",
    "def f():\n    'doc'\n    global a, b\n    a = 1\n\ndef g():\n    x = 1\n    def h():\n        nonlocal x\n        x = 2\n",
    "@d\ndef f(): pass", "@a.b(c)\n@d\n\n# comment\ndef f(x):\n    return x\n", "@(lambda f: f)\ndef g(): pass",
    "if a:\n    @d\n    def f():\n        pass\n",
    "for x in y: pass", "for a, b in c:\n    pass\nelse:\n    break\n", "for (a, b) in c: pass", "for [a, b] in c: pass",
    "for *a, b in c: pass", "for x, in y: pass", "for a.b in c: pass", "for a[0] in c: pass", "for x in *a, b: pass",
    "for x in a, b: pass", "for x in a if b else c:\n    continue\n", "for i in range(10):\n    for j in i:\n        pass\n",
    "for x in y:\n    pass\nx = 1\n", "for x in (yy): pass", "for ((a), b) in c: pass",
    "global a", "global a, b", "nonlocal a", "del a", "del a, b", "del (a, b)", "del a,", "del [a, b]", "del a.b, c[0]",
    "del (a), (b)", "del ()", "del (a)", "del a[1], (b, [c, d])",
    "assert a", "assert a, 'msg'", "assert (a, b)", "assert a if b else c, (d)",
    "raise", "raise E", "raise E('x') from None", "raise (E)", "raise E from (c)",
    "try:\n    pass\nexcept:\n    pass\n", "try: pass\nexcept E: pass", "try: pass\nfinally: pass",
    "try:\n    a\nexcept E as e:\n    b\nexcept (F, G):\n    c\nelse:\n    d\nfinally:\n    e\n",
    "try:\n    a\nexcept E:\n    b\nelse:\n    c\n", "try:\n    a\nexcept:\n    b\nexcept E:\n    c\n",
    "try:\n    try:\n        a\n    finally:\n        b\nexcept a.b as c:\n    raise\n",
    "def f():\n    try:\n        return 1\n    except E:\n        pass\n    x = 2\n",
    "with a: pass", "with a as b: pass", "with a as b, c as d:\n    pass\n", "with a, b: pass", "with (a, b): pass",
    "with (a as b): pass", "with (a as b, c as d,): pass", "with (a, b) as c: pass", "with (a) as b: pass", "with (a).b: pass",
    "with (a): pass", "with (): pass", "with a as (b, c): pass", "with a as [b, *c]: pass", "with a as b.c, d as e[0]: pass",
    "with (\n    a as b,\n    c as d\n):\n    pass\n", "with f(x) as y, (g(z)): pass", "with (a, b), c: pass", "with (yy) as b, c: pass",
    "match in x", "x = [i, in_]", "*a = 1", "*a, = 1", "[*a] = 1", "for *a in y: pass", "with a as *b: pass", "with a as *b, c: pass",
]
# P5: imports. alias spans run from the first name token to the asname; ImportFrom ends at `)`.
STATEMENTS += [
    "import a", "import a.b.c", "import a as b", "import a.b as c, d, e.f as g", "import a . b", "import a; import b;",
    "from a import b", "from a.b import c as d, e", "from a import (b)", "from a import (b, c,)", "from a import (b as c, d as e)",
    "from a import (\n    b,\n    c as d,  # note\n)\n", "from a import *", "from . import a", "from .. import a", "from ... import a",
    "from .... import a", "from ..... import a", "from .a import b", "from ..a.b import c", "from ...a import b", "from . . import a",
    "from .import a", "from . a import b", "from .a import *", "from __future__ import annotations", "from a import b as c; x = 1",
    "from a \\\n    import b", "if a:\n    import b\nelse:\n    from c import d\n", "def f():\n    from . import g\n    return g\n",
    "try:\n    import a\nexcept ImportError:\n    a = None\n", "import match, case", "from match import case as _",
    "from a import (b as c)", "import a  # é",
]
# P6: classes. ClassDef starts at `class` (decorators excluded) and ends with its body.
STATEMENTS += [
    "class A: pass", "class A(): pass", "class A(B): pass", "class A(B, C,): pass", "class A(B, metaclass=M): pass",
    "class A(metaclass=M, **kwds): pass", "class A(*bases, **kwds): pass", "class A(B.C, D[E], f(x), x=1, *y): pass",
    "class A(B,\n        C):\n    pass\n", "@d\nclass A: pass", "@d1\n@d2(x)\n@a.b\nclass A(B):\n    pass\n",
    "class A:\n    \"\"\"doc\"\"\"\n", "class A:\n    'doc'\n    x = 1\n    def f(self):\n        return self.x\n",
    "class A:\n    class B:\n        class C(A): pass\n    y = B\n", "class A:\n    @staticmethod\n    def f(): pass\n    @d\n    class B: pass\n",
    "def f():\n    class A(object):\n        pass\n    return A\n", "if a:\n    class A: pass\nelse:\n    class A(B): x = 1; y = 2\n",
    "class A: x = 1; y = 2", "class A(B): import c", "class match: pass", "class A(B if c else D, lambda: 1): pass",
    "class A:\n\n    # comment\n\n    def f(self): pass\n\n    # trailing\nx = 1\n", "class A(\n    B,  # note\n    metaclass=M,\n):\n    pass\n",
    "class A:\n    def __init__(self, a, *b, c=1, **d):\n        self.a = a\n        for i in b:\n            try:\n                pass\n            finally:\n                del i\n",
    "@d(x)\nclass A(B, *c, metaclass=M, **k):\n    \"doc\"\n    class C: pass\n    def f(self):\n        return 1\nclass D(): y = 1\n",
    "class A: pass  # é", "class A(x=1, *y): pass", "class A(**k, x=1): pass",
]

INVALID = [
    "'\0'", "#\0",
    "b'a' 'b'",
    "(*a)", "f(**a,*b)", "{*a:b}", "[*a if b else c]",
    "x =", "1 = x", "f() = x", "(a+b) = c", "[a,1] = c", "a,b += c",
    "if x\n pass", "if x:\npass", "if x: if y: pass", "else: pass",
    "x y", "f(a b)", "[a b]", "{a b}", "f(x=1,2)", "a + not b",
    "a is not", "a not b", "(]", "'''unfinished", "if x:\n    pass\n  pass",
    "lambda x y: x", "1 + lambda: 1", "not lambda: 1", "lambda a=1, b: a", "lambda *: 1", "lambda *, **k: 1",
    "lambda /: 1", "lambda a, /, b, /: 1", "lambda *a, *b: 1", "lambda **k, a: 1", "lambda *, /: 1",
    "def f(a=1, b): pass", "def f(*): pass", "def f(*,): pass", "def f(**k, a): pass", "def f(/): pass", "def f(*a=1): pass",
    "def f(a, *, /): pass", "def f: pass", "def f()", "def f(a b): pass", "def (a): pass", "@d\nx = 1", "@d", "def f() -> : pass",
    "for x y: pass", "for x in: pass", "for 1 in y: pass", "for a + b in y: pass", "for f() in y: pass",
    "for x in y: pass\nelse x", "a, in b",
    "global", "global a.b", "global a,", "nonlocal 1", "del", "del 1", "del a + b", "del *a", "del *a, b", "del f()", "del (*a, b)",
    "assert", "assert a,", "raise from x", "raise a from", "raise a, b",
    "try: pass", "try: pass\nelse: pass", "try: pass\nelse: pass\nfinally: pass", "try: pass\nexcept E as: pass",
    "try: pass\nexcept E as a.b: pass", "try: pass\nexcept E, F: pass", "try: pass\nfinally: pass\nexcept: pass",
    "try: pass\nexcept as e: pass", "except: pass", "finally: pass",
    "class", "class A", "class: pass", "class A(: pass", "class A(B: pass", "class A) : pass", "class A(B)", "class 1: pass", "class A.B: pass",
    "class A(B,,): pass", "class A(x=1, y): pass", "class A(**k, *y): pass", "class if: pass", "class A:", "class A:\npass", "class A pass",
    "@d\nx = 1", "@d\nimport a", "@\nclass A: pass", "@d class A: pass", "class A[B]: pass", "class A(B) -> C: pass", "x = class A: pass",
    "import", "import a,", "import a.", "import .a", "import a as", "import a as b.c", "import (a)", "import *", "import a b", "import if",
    "from a", "from import b", "from a import", "from a import b,", "from a import ()", "from a import (b", "from a import (*)",
    "from a import *, b", "from a import b, *", "from a import b.c", "from a import (b.c)", "from a. import b", "from a import b as",
    "from a import b as 1", "from .. import", "from a import (b,,)", "from a import (,)", "x = import a", "from a import b c",
    "with: pass", "with a as: pass", "with a as 1: pass", "with a, : pass", "with a as f(): pass", "with (a as b) as c: pass",
]

UNSUPPORTED = [
    "K", "a.K", "f(K=1)", "match x:\n    case _: pass\n",
    "import é", "import a as é", "from é import a", "from a import é", "from a import b as é", "class é: pass", "class A(é): pass", "class A(é=1): pass", "class A(B[1:2]): pass", "class A:\n    x: int = 1\n", "class A:\n    async def f(self): pass\n", "@d\nclass A:\n    def f(self): yield\n", "async def f(): pass", "@d\nasync def f(): pass",
    "async for x in y: pass", "async with a: pass", "def f(): yield", "def f(): x = yield y", "lambda: (yield)", "def f(é): pass", "lambda é: 1",
    "global é", "try: pass\nexcept E as é: pass", "try: pass\nexcept* E: pass", "def f(): await x", "def f(a: int): x: int = 1", "for x in [y for y in z]: pass",
    "[x for x in y]", "{x for x in y}",
    "{x:x for x in y}", "f(x for x in y)", "a[1:2]", "a[:2]", "f'{x}'",
    "(x := 1)", "with (x := 1): pass", "with a[1:2]: pass",
]
