print("hello world")
print('single quotes')
print("it's fine")
print('say "hi"')
print("")
print("tab:\there")
print("nl:\nnext")
print("mix" + "ed" + "up")
print("ab" "cd")
s = "abc"
t = s + "de"
print(t)
print(t == "abcde")
print(t == "abcdf")
print(t != "abcde")
print("a" == "a", "a" == "b")
print("" == "", 1 == "1", "1" == 1)
print(t != "abcde", "x" != "x")
print(t == "abc" + "de")
print(len("hello"))
print(len(s), len(""), len("a b c"))
u = s + s
print(len(u) + len(t))
print(not "")
print(not "x")
print(True and "yes")
print("" or 7)
